### ISSUE TITLE
Prettify Issue Template

### ISSUE THREAD

**Issue by lorderikir** [monPlan/AppleSeed#68]
Prettify The template for Issues

**Comment by dsalahutdinov** [comment]
Hi, can I take this one to do?

**Comment by lorderikir** [comment]
@dsalahutdinov yes

**Comment by dsalahutdinov** [comment]
Do you have some suggestions about it or things you want to see there?

**Comment by lorderikir** [comment]
https://github.com/stevemao/github-issue-templates/blob/master/simple/ISSUE_TEMPLATE.md

Also make a pull request template 
https://github.com/stevemao/github-issue-templates/blob/master/simple/PULL_REQUEST_TEMPLATE.md

Thanks
