### ISSUE TITLE
Issue while updating an entity

### ISSUE THREAD

**Issue by ashlindias06** [monPlan/AppleSeed#78]
**Summary of Issue**: While trying to update (making a PUT request), I get an error "CREATE operation failed: code <some_code> is already in use". I did not change the code, just sent the same existing code back to the service, when I tried to make a put request without sending a code, the update worked but this time the code was set to null. 

**Impact**: I am trying to implement the update functionality, which is difficult to achieve with this issue.

## System Details
- **Operating System**: Mac OS High Sierra
- **Operating System Version**: v10.13.1
- **Java Version**:1.8
- **IDE**: IntelliJ IDEA
- **Error Message**: CREATE operation failed: code <some_code> is already in use

## Expected Behavior
The entity I am trying to edit must be edited with all new fields along with the old Code

## Current Behavior
The code is still the old one, but I get an error saying code already exists. If I send no code, it updates the code to null.

## Reproduction
I can explain with an example,
I have UNIT entity, with 
unitId, unitCode, unitName
and has the following data in it,
unitId     unitCode      unitName
1             u001             unit01
2            u002             unit02
3             u003            unit03

when I make a PUT request like this and Pass the JSON,

<details>
<summary>PUT /api/unit/1</summary>
{
"unitCode":"u001",
"unitName":"unit0101"
}
</details> 

I get the following error message,
{
    "message": "CREATE operation failed: code PROJ2020 is already in use."
},

Also, if I remove the unitCode this time,
{
"unitName":"unit0101"
}
what it does is makes the unitCode null,
unitId     unitCode      unitName
1             null             unit01
2            u002             unit02
3             u003            unit03

## Possible Solution/s
I had a look at the generic code created in the MonPlanService.java class,
at line 101, "`if (this.repository.getByCode(modelInstance.fetchCode()).size() > 0) {`"
causes that problem.
I feel the idea of having this validation was noble considering the security aspect, but it can be done some other way, without affecting the main functionality.

Thanks & Regards,
Ashlin Dias

**Comment by ashlindias06** [comment]
Hi,
I made the following change to that fixed this bug,
in MonPlanService.java, added
**line 101**: 

> if (!(this.repository.getById(modelInstance.getId()).fetchCode()).equals(modelInstance.fetchCode())
>                     && (this.repository.getByCode(modelInstance.fetchCode()).size() > 0)) {

instead of

>  "if (this.repository.getByCode(modelInstance.fetchCode()).size() > 0) {"

>

**Comment by lorderikir** [comment]
resolved in #80
